name: drv

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Select the branch"
        required: false
        default: "master"
        type: string

jobs:
  Build:
    runs-on: windows-2019
    timeout-minutes: 45

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: ${{ inputs.branch }}
          repository: sandboxie-plus/Sandboxie

      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v1.3

      - name: Patch
        shell: pwsh
        run: |
          $content = Get-Content -Path "Sandboxie/core/drv/verify.c" -Raw
          $newContent = $content -replace "return status;`n}", "Verify_CertInfo.valid = 1;`n`nreturn 1;`n}"
          Set-Content -Path "Sandboxie/core/drv/verify.c" -Value $newContent

      - name: Build Sandboxie x64
        run: msbuild /t:build Sandboxie\Sandbox.sln /p:Configuration="SbieRelease" /p:Platform=x64 -maxcpucount:8

      - name: Get Sign Cert
        env:
          PFX_BASE64: ${{ secrets.PFX_BASE64}}
          CER_CONTENT: ${{ secrets.CER_CONTENT }}
        run: |
          New-Item -ItemType directory -Path certificate
          Set-Content -Path certificate\certificate.txt -Value $env:PFX_BASE64
          certutil -decode certificate\certificate.txt certificate\certificate.pfx
          Set-Content -Path certificate\intermediate.txt -Value $env:CER_CONTENT
          certutil -decode certificate\intermediate.txt certificate\intermediate.crt

      - name: Sign executable
        env:
          PFX_PASSWORD: ${{ secrets.PFX_PASSWORD}}
        run: |
          set message=%DATE%
          date 2014/1/1
          signtool sign /v /ac certificate\intermediate.crt /f certificate\certificate.pfx /fd SHA1 /p %env:PFX_PASSWORD% Installer/SbiePlus_x64/SbieDll.dll
          date %message%

      - name: Upload Sandboxie x64 drv
        uses: actions/upload-artifact@v3
        with:
          name: Sandboxie_x64_drv
          path: |
            Installer/SbiePlus_x64/SbieDll.dll
          retention-days: 1
