name: CI

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Select the branch"
        required: false
        default: "master"
        type: string

jobs:
  Build:
    runs-on: windows-2019
    timeout-minutes: 45

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: ${{ inputs.branch }}
          repository: sandboxie-plus/Sandboxie

      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v1.3

      - name: Patch
        shell: pwsh
        run: |
          $content = Get-Content -Path "Sandboxie/core/drv/verify.c" -Raw
          $newContent = $content -replace "return status;`n}", "Verify_CertInfo.valid = 1;`n`nreturn 1;`n}"
          Set-Content -Path "Sandboxie/core/drv/verify.c" -Value $newContent

      - name: Build Sandboxie x86
        run: msbuild /t:build Sandboxie\Sandbox.sln /p:Configuration="SbieRelease" /p:Platform=Win32 -maxcpucount:8

      - name: Build Sandboxie x64
        run: msbuild /t:build Sandboxie\Sandbox.sln /p:Configuration="SbieRelease" /p:Platform=x64 -maxcpucount:8

      - name: Build Sandboxie ARM64
        run: msbuild /t:build Sandboxie\Sandbox.sln /p:Configuration="SbieRelease" /p:Platform=ARM64 -maxcpucount:8

      - name: Build Sandboxie ARM64EC
        run: msbuild /t:build Sandboxie\Sandbox.sln /p:Configuration="SbieRelease" /p:Platform=ARM64EC -maxcpucount:8

      - name: Install Qt6 x64
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.3.1'
          arch:  'win64_msvc2019_64'
          cache: true

      - name: Install Qt6 ARM64
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.3.1'
          arch:  'win64_msvc2019_arm64'
          cache: true

      - name: Install Qt5 x64
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          arch:  'win64_msvc2019_64'
          cache: true

      - name: Install Qt5 x86
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          arch:  'win32_msvc2019'
          cache: true

      - name: Installing Jom
        run: SandboxiePlus\install_jom.cmd

      - name: Build Sandboxie-Plus x64
        run: SandboxiePlus\qmake_plus.cmd x64

      - name: Build SbieShell x64
        run: msbuild /t:restore,build -p:RestorePackagesConfig=true SandboxiePlus\SbieShell\SbieShell.sln /p:Configuration="Release" /p:Platform=x64

      - name: Build Sandboxie-Plus ARM64
        run: SandboxiePlus\qmake_plus.cmd ARM64

      - name: Build SbieShell ARM64
        run: msbuild /t:restore,build -p:RestorePackagesConfig=true SandboxiePlus\SbieShell\SbieShell.sln /p:Configuration="Release" /p:Platform=ARM64

      - name: Build Sandboxie-Plus x86
        run: SandboxiePlus\qmake_plus.cmd Win32

      - name: Build Sandboxie-Tools x86
        run: msbuild /t:build SandboxieTools\SandboxieTools.sln /p:Configuration="Release" /p:Platform=x86 -maxcpucount:8

      - name: Build Sandboxie-Tools x64
        run: msbuild /t:build SandboxieTools\SandboxieTools.sln /p:Configuration="Release" /p:Platform=x64 -maxcpucount:8

      - name: Build Sandboxie-Tools ARM64
        run: msbuild /t:build SandboxieTools\SandboxieTools.sln /p:Configuration="Release" /p:Platform=ARM64 -maxcpucount:8
        
      - name: Add missing languages for Qt5 x86 (issue 1528)
        run: Installer\fix_qt5_languages.cmd Win32

      - name: Add Windows 7 compatible Qt6 DLLs
        run: Installer\fix_qt6_win7.cmd

      - name: Merging Builds
        run: Installer\merge_builds.cmd

      - name: Collect installer assets
        run: Installer\get_assets.cmd

      - name: Sign executable
        env:
          PFX_BASE64: ${{ secrets.PFX_BASE64}}
          CER_CONTENT: ${{ secrets.CER_CONTENT }}
          PFX_PASSWORD: ${{ secrets.PFX_PASSWORD}}
        shell: pwsh
        run: |
          @"
          New-Item -ItemType directory -Path certificate
          Set-Content -Path certificate\certificate.txt -Value `$env:PFX_BASE64
          certutil -decode certificate\certificate.txt certificate\certificate.pfx
          Set-Content -Path certificate\intermediate.txt -Value `$env:CER_CONTENT
          certutil -decode certificate\intermediate.txt certificate\intermediate.crt
          Get-Date
          `$currentTime = Get-Date
          Set-Date -Date "2014-04-01"
          Get-Date
          & 'C:/Program Files (x86)/Windows Kits/10/bin/10.0.17763.0/x86/signtool.exe' sign /fd SHA1 /p `$env:PFX_PASSWORD /ac certificate\intermediate.crt /f certificate\certificate.pfx Installer/SbiePlus_x64/SbieDll.dll
          Set-Date `$currentTime
          Remove-Item -Recurse -Force certificate
          "@ | Out-File -FilePath "sign.ps1"
          ./sign.ps1 -RunAsAdmin
          
      - name: Upload installer assets
        uses: actions/upload-artifact@v3
        with:
          name: Assets
          path: |
            Installer/Assets/*
          retention-days: 1

      - name: Upload Sandboxie x64
        uses: actions/upload-artifact@v3
        with:
          name: Sandboxie_x64
          path: |
            Installer/SbiePlus_x64/*
          retention-days: 1

      - name: Upload Sandboxie ARM64
        uses: actions/upload-artifact@v3
        with:
          name: Sandboxie_ARM64
          path: |
            Installer/SbiePlus_a64/*
          retention-days: 1

      - name: Upload Sandboxie x86
        uses: actions/upload-artifact@v3
        with:
          name: Sandboxie_x86
          path: |
            Installer/SbiePlus_x86/*
          retention-days: 1

      - name: Upload Sandboxie drv
        uses: actions/upload-artifact@v3
        with:
          name: Sandboxie_x64_drv
          path: |
            Installer/SbiePlus_x64/SbieDll.dll
            Installer/SbiePlus_a64/SbieDll.dll
            Installer/SbiePlus_x86/SbieDll.dll
          retention-days: 1
